<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SmartLang.Broker</AssemblyName>
    <RootNamespace>SmartLang.Broker</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\SmartLang\Assets\SmartLang.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartLang.Runtime\SmartLang.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\SmartLang.NativeHook\bin\SmartLang.NativeHook.dll"
          Link="SmartLang.NativeHook.dll"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest"
          ExcludeFromSingleFile="true" />
    <None Include="..\SmartLang.NativeHook\bin\SmartLang.NativeHook32.dll"
          Link="SmartLang.NativeHook32.dll"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest"
          ExcludeFromSingleFile="true" />
    <None Include="..\SmartLang.NativeHost32\bin\SmartLang.NativeHost32.exe"
          Link="SmartLang.NativeHost32.exe"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest"
          ExcludeFromSingleFile="true" />
  </ItemGroup>

</Project>
